# Generated by Django 2.1.1 on 2018-11-14 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefdecuisine', '0002_souschef_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souschef',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
