# Generated by Django 2.1.1 on 2018-11-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chefdecuisine', '0003_auto_20181114_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='souschef',
            name='owner',
        ),
        migrations.AddField(
            model_name='useracc',
            name='chef_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='chefdecuisine.sousChef'),
        ),
    ]
